title: Ben Brady
locale: "en-us"
email: benbradybusiness@gmail.com
description: >-
  Software Engineer
baseurl: ""
url: "https://hireme.contact"
logo: "/images/logo.png"
twitter:
  username: Ben-Brady

# Build settings
markdown: kramdown
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-feed

permalink: /:categories/:title/
skin: "/assets/css/skins/light.css"
search_full_content: false

collections:
  projects:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: post
      comments: true
      share: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
